[package]
name = "ssss-rs-core"
version.workspace = true
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.10.0" }

[dev-dependencies]
test-case = "3.3.1"
